version: '3'

services:
  krypt-db:
    image: postgres:15.3
    container_name: krypt-db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
    volumes:
      - krypt-db:/var/lib/postgresql/data

volumes:
  krypt-db:
