version: '3.8'

services:
  server:
    build:
      context: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'

  db:
    image: postgres
    restart: always
    container_name: kryptdb
    environment:
      POSTGRES_PASSWORD: pass123
      DATABASE_URL: postgresql://postgres:pass123@kryptdb:5432
    ports:
      - '5433:5432'
    volumes:
      - kryptvol:/var/lib/postgresql/data

volumes:
  kryptvol:
